### ISSUE TITLE
KeyError: 'model_ema.diffusion_modeltime_embed0weight'

### ISSUE THREAD

**Issue by NaughtDZ** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#19]
Using half precision

    ---------------------
         ITERATION 1
    ---------------------

new alpha = 0.05

Traceback (most recent call last):
  File "I:\Dreambooth-Stable-Diffusion\Merge-Stable-Diffusion-models-without-distortion\SD_rebasin_merge.py", line 55, in <module>
    theta_0 = {key: (1 - (new_alpha)) * theta_0[key] + (new_alpha) * value for key, value in theta_1.items() if "model" in key and key in theta_1}
  File "I:\Dreambooth-Stable-Diffusion\Merge-Stable-Diffusion-models-without-distortion\SD_rebasin_merge.py", line 55, in <dictcomp>
    theta_0 = {key: (1 - (new_alpha)) * theta_0[key] + (new_alpha) * value for key, value in theta_1.items() if "model" in key and key in theta_1}
KeyError: 'model_ema.diffusion_modeltime_embed0weight'

**Comment by vaguenebula** [comment]
what models are you trying to merge?

**Comment by NaughtDZ** [comment]
> what models are you trying to merge?

Anything-V3.0 and wd-v1-3-float16

**Comment by wilhelmw201** [comment]
maybe you can try removing the ema first with a tool like this one https://github.com/Akegarasu/sd-model-converter
