### ISSUE TITLE
float32 mode broken?

### ISSUE THREAD

**Issue by wilhelmw201** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#27]
after the first iteration i get the following error, when i use float32 mode to merge models

Traceback (most recent call last):
  File "E:\stablediffu\stable-diffusion-webui\models\Stable-diffusion\Merge-Stable-Diffusion-models-without-distortion-main\SD_rebasin_merge.py", line 65, in <module>
    first_permutation, y = weight_matching(permutation_spec, flatten_params(model_a), theta_0, usefp16=args.usefp16)
  File "E:\stablediffu\stable-diffusion-webui\models\Stable-diffusion\Merge-Stable-Diffusion-models-without-distortion-main\weight_matching.py", line 849, in weight_matching
    A += torch.matmul(w_a, w_b).cpu()
RuntimeError: expected scalar type Float but found Half

**Comment by RedAndr** [comment]
```python
            w_a = torch.moveaxis(w_a, axis, 0).reshape((n, -1)).to("cpu").to(torch.float32)
            w_b = torch.moveaxis(w_b, axis, 0).reshape((n, -1)).T.to("cpu").to(torch.float32)
            A += torch.matmul(w_a, w_b).cpu()
```

**Comment by ogkalu2** [comment]
Missed this sorry. Should work now.
